config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'post/index'
  root 'posts#index'
  devise_for :users
  notify_to :users, with_devise: :users
  # notify_to :users
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :users
  resources :friendship
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
  acts_as_notifiable :users,
                     targets: ->(comment, _key) {
                       ([comment.recipe.user] + comment.recipe.commented_users.to_a - [comment.user]).uniq
                     },
                     notifiable_path: :recipe_notificable_path

  def recipe_notificable_path
    recipe_path id: recipe.id
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :find_comment, only: %i[update edit destroy]
  before_action :find_post, only: %i[index edit destroy]
  def index
    respond_to do |format|
      format.html do
        render 'index', layout: false, locals: { post: @post }
      end
    end
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      count_comments = @comment.post.comments.count
      respond_to do |format|
        format.html do
          render 'create', layout: false, locals: { comment: @comment, count_comments: count_comments }
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.html do
        render 'edit', layout: false, locals: { comment: @comment, post: @post }
      end
    end
  end

  def update
    if @comment.update(comment_params)
      count_comments = @comment.post.comments.count
      respond_to do |format|
        format.html do
          render 'create', layout: false, locals: { comment: @comment, count_comments: count_comments }
        end
      end
    end
  end

  def destroy
    if @comment.destroy
      count_comments = @post.comments.count
      respond_to do |format|
        format.json { render json: { count_comments: count_comments } }
      end
    end
  end

  private

  def find_post
    @post = Post.find_by(id: params[:post_id])
    render 'shared/_404' if @post.nil?
  end

  def find_comment
    @comment = Comment.find_by(id: params[:id])
    render 'shared/_404' if @comment.nil?
  end

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/create.html.erb
<div class = "comment-user">
  <div class = "avt-user">
    <%= image_tag 'jeans2.jpg', alt: 'avatar' %>
  </div>
  <div class = "comment">
    <div class = "cm-1">
      <span class = "user-name"><a><%= comment.user.name %></a></span>
      <span class = "user-cm"><%= comment.content %></span>
    </div>
    <div class = "lkandcm-cm">
      <a class = "like-cm" href = "">Like</a>
      <a class = "comment-cm" href = "">Comment</a>
      <p hidden><%= count_comments %> Comment</p>
      <span style = "color: #657786;"><%= time_ago_in_words(comment.updated_at) %></span>
    </div>
  </div>
  <div class="cmandedit">
    <span style = "font-size: 18px;color: #9F9FA9;">...</span>
    <div class="dropdown-cmandedit">
      <div class = "edit-cm" data-id = "<%= comment.id%>" data-post = "<%= comment.post.id %>">
        <span><i class="fa fa-pencil"></i> Edit</span>
      </div>
      <div class = "delete-cm"  data-id = "<%= comment.id%>" data-post = "<%= comment.post.id %>">
        <span><i class="fa fa-trash-o"></i> Delete</span>
      </div>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<div class = "write-text">
  <%= form_for  edit_post_comment_path(@comment), html: {id: 'edit-comment', data_post: post.id, data_id: @comment.id}  do |comment| %>
    <div class="form-wr">
      <%= comment.text_field :content, class: "ip-comment", placeholder: "Write comment...", autocomplete: 'off', value: "#{@comment.content}" %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class = "comment-box">
  <% post.comments.each do |comment| %>
    <div class = "comment-user">
      <div class = "avt-user">
        <%= image_tag 'jeans2.jpg', alt: 'avatar' %>
      </div>
      <div class = "comment">
        <div class = "cm-1">
          <span class = "user-name"><a><%= comment.user.name %></a></span>
          <span class = "user-cm"><%= comment.content %></span>
        </div>
        <div class = "lkandcm-cm">
          <a class = "like-cm" href = "">Like</a>
          <a class = "comment-cm" href = "">Comment</a>
          <span style = "color: #657786;"><%= time_ago_in_words(comment.updated_at) %></span>
        </div>
      </div>
      <%if comment.user ==  current_user %>
      <div class="cmandedit">
        <span style = "font-size: 18px;color: #9F9FA9;">...</span>
        <div class="dropdown-cmandedit">
          <div class = "edit-cm" data-id = "<%= comment.id%>" data-post = "<%= post.id %>">
            <span><i class="fa fa-pencil"></i> Edit</span>
          </div>
          <div class = "delete-cm"  data-id = "<%= comment.id%>" data-post = "<%= post.id %>">
            <span><i class="fa fa-trash-o"></i> Delete</span>
          </div>
        </div>
      </div>
      <% end %>
    </div> 
  <% end %>
  <div class = "comment-text">
    <div class = "comment-user-1">
      <div class = "avt-user">
        <%= image_tag 'jeans2.jpg', alt: 'avatar' %>
      </div>
      <div class = "write-text">
        <%= form_for new_post_comment_path, html: {id: 'add-comment', data: post.id, hidden: false}  do |comment| %>
          <div class="form-wr">
            <%= comment.text_field :content, class: "ip-comment", placeholder: "Write comment...", autocomplete: 'off' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>