config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'post/index'
  root 'posts#index'
  devise_for :users
  notify_to :users, with_devise: :users
  # notify_to :users
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :users
  resources :friendship
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_base64_uploader :avatar, AvatarUploader
  acts_as_notification_target
  validates :name, presence: true, length: { maximum: 50 }
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_request, dependent: :destroy, foreign_key: 'user_request', class_name: 'user_response'
  has_many :user_response, dependent: :destroy, foreign_key: 'user_response', class_name: 'user_response'

  def self.search(term)
    where('name LIKE ?', "%#{term}%") if term
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :find_user, only: %i[edit update show]
  def index
    @users = User.search(params[:term])
    respond_to :js
  end

  def show
    @posts = @user.posts.page(params[:page]).per(5)
    render_load_perpage && return if request.xhr?
  end

  def edit
    respond_to do |format|
      format.html do
        render 'edit', layout: false
      end
    end
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.json { render json: @user }
      end
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    render 'shared/_404' if @user.nil?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

  def render_load_perpage
    render 'posts/_pagekaminari', layout: false
  end
end

app/views/users/_search_user_result.html.erb
<% if users.present? %>
  <% users.each do |user| %>
    <div class="search-ava-link" >
      <div class="avt-search-us" >
        <%= image_tag user.avatar.url, alt: 'avatar.jpg', id: 'avt-s1' %>
      </div>
      <%= link_to user_path(user) ,class: 'link_user' do %>
      <div class="search-result-item" ><%= user.name %></div>
    <% end %>
    </div>
  <% end %>
<% else %>
  <div class = "noresult">
    No results found
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, html: {id: 'edit-user-form', data: current_user.id} do |f| %>
  <%= render 'shared/errors_mess', object: @user %>
  <div class="container c-user-edit">
    <h1><b>Profile</b></h1>
    <hr>
      <div class = "img-edit-u">
        <div class = "img-edit-u1">
          <%= image_tag "#{@user.avatar}", alt: 'avatar.jpg', id: 'output-img-edit' %>
        </div>
         <%= f.file_field :avatar, class: 'btn btn-light', accept:"image/*", onchange:"loadFile(event)" %>
      </div>

      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Enter Name", value:"#{@user.name}", autocomplete: 'off' %>

      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "Enter Email", value:"#{@user.email}", autocomplete: 'off' %>

       <label>
        <input type="checkbox" class = "checked-box" name="remember" style="margin-bottom:15px" > Change Password
      </label>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Enter Password", disabled: true %>

    <div class="user-edit-b">
      <button type="button" class="cancelbtn">Cancel</button>
      <button type="submit" class="editbtn">Edit</button>
    </div>
  </div>
<% end %>

app/views/users/index.js.erb
$("#users-result").html('<%= j render "search_user_result", {users: @users} %>')

app/views/users/show.html.erb
<div class = "container">
  <div  class = "user-information">
    <div class = "avatar-user-wall">
      <div class = "img-wall">
        <%= image_tag @user.avatar.url, alt: 'avatar.jpg' %>
      </div>
    </div>
    <div class = "info-uswall">
      <div class = "email-fsh">
        <h3><%=@user.email%></h3>
        <%= form_for new_friendship_path, html: {class:'btn-addfriend'} do |f|%>
          <%= f.hidden_field:user_response, value: "#{@user.id}", name:'friendship[user_response]', id: 'user-rsp' %>
          <button type="submit" class="btn btn-light btn-md">Add Friend</button>
        <% end %>
      </div>
      <div class = "info-pfl">
        <span><b><%= @user.posts.count %></b> posts</span>
        <span><b>0</b> followers</span>
        <span><b>0</b> following</span>
      </div>
      <div class = "ifuser-name"><span><%=@user.name %></span></div>
    </div>
  </div>
  <div id="all_post">
    <% @posts.each do |post| %>
      <%= render 'posts/listposts', post: post  %>
    <% end%> 
  </div>
</div>
<%# #TODO
check nil?
rubocop
loi save() va ;
 %>